### ISSUE TITLE
Broken link on home page

### ISSUE THREAD

**Issue by impressivewebs** [robhrt7/MCSS#14]
On here:

http://operatino.github.io/MCSS/

You have a link to the "issues section on GitHub" that points to:

http://operatino.github.io/issues

Which doesn't exist. Should be:

https://github.com/operatino/MCSS/issues/

**Comment by robhrt7** [comment]
Thanks for report! Fixed this issue with 2f7cb0752dd903eee2dad2e127762f19d8dc260f
