### ISSUE TITLE
Separate file for cascade rules

### ISSUE THREAD

**Issue by itrelease** [robhrt7/MCSS#15]
How about using separate file for cascade rules, for example we have two modules

```
/* toolbar.css */
.Toolbar {
  ...
}

/* menu.css */
.Menu {
  ...
}
```

and if we need to change menu in toolbar we can create another file toolbar_menu.css or even toolbar>menu.css so it would be more clearly where things was overwritten.

**Comment by robhrt7** [comment]
With MCSS you can handle files whatever you like, just stick to one rule - separate layer modules. 

This means that you can store all modules in one file, separating CSS rules with comments, like this:

``` css
/* Base layer
---------------------------------------------------------------------------------- */
.base-module {}
/* /Base layer
---------------------------------------------------------------------------------- */

/* Project layer
---------------------------------------------------------------------------------- */
.project-module {}
/* /Project layer
---------------------------------------------------------------------------------- */
```

In separate files likes this

```
base
  forms.css
  forms_light.css

project
  login.css
```

Or in deeper nested files

```
base
  forms
    main.css
    light.css

project
  login.css
```
