### ISSUE TITLE
What is multilayer CSS?

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [robhrt7/MCSS#16]
As a criticism of the documentation here: http://operatino.github.io/MCSS/en/

it starts by telling me some ideological underpinnings. So it's like OOCSS (assuming I know about OOCSS). Then it says it's recommended for other teams as documentation?? That has to be a mistranslation. 

it was created for big teams but can be used on small teams and the documentation is being improved.

What is MCSS? The introduction didn't tell me.

The next section is called Main Principles.

It tells me that MCSS is very independent(?), doesn't have a specific style
 (is MCSS something that would have a style?),and doesn't focus on the layout of files. It then introduces the concept of blocks (blocks?) 

From this point it starts citing examples

What is MCSS?

**Comment by robhrt7** [comment]
Hello, thanks for your comment, I assume that translation could be not so exact, but we're ready to improve it:

> Then it says it's recommended for other teams as documentation?? That has to be a mistranslation.

Documentation for code writing principles, maybe you'll suggest a better word for that?

> It tells me that MCSS is very independent(?), doesn't have a specific style
> (is MCSS something that would have a style?),and doesn't focus on the layout of files. It then introduces the concept of blocks (blocks?)

I improved Main principles section a little bit, and as I see, the main misunderstanding is about blocks concept? 

Maybe the problem rises from the roots of methodology, as we took some ideas from BEM (block element modifier), I assumed that Block definition is familiar to everyone who read MCSS documentation. I think, that if I'll write some more about main principles of blocks on CSS, it will be more easier to understand the idea of MCSS.

In nearest future, we'll also add some more detailed description of other parts of MCSS documentation, as for now, in english, we have only intro part.

**Comment by Ghoughpteighbteau** [comment]
So MCSS is a "style guideline" that would be a concise description. 

A guideline to structure your CSS. 

The translation isn't exact, and that contributed to my confusion. It doesn't need to be perfect however, it's just when I was introduced to it, I had no concept of what it was.

**Comment by robhrt7** [comment]
Thanks for your thoughts, going to update project description in next few days!
