### ISSUE TITLE
Ошибка в примере с бутстрепом 

### ISSUE THREAD

**Issue by amelekesov** [robhrt7/MCSS#6]
На странице http://operatino.github.com/MCSS/examples/mcss_with_bootstrap/ в секции All layers together описвается классы pres-section за ним pres-section_header и под ним pres-descr судя по документации должно быть pres-section_descr. Или я что то не так понял ?

**Comment by robhrt7** [comment]
Дельное замечание, презентационная разметка была не по MCSS, поправил - 9471adb2a9c23f892085d1352ec81f533fcf7eb7
